services:
  - type: web
    name: musify-backend
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
